# Generated by Django 3.1.2 on 2020-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matkul',
            name='desc',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matkul',
            name='nama',
            field=models.TextField(default='', max_length=30),
        ),
    ]
